package ueg.watchdog.view;

import ueg.watchdog.core.configuration.WatchDogContext;
import ueg.watchdog.util.SettingsHandler;

import javax.swing.*;

import static ueg.watchdog.Constants.VideoConstants.VIDEO_STORAGE_PATH;
import static ueg.watchdog.core.configuration.WatchDogContext.OperatingMode;

/**
 * @author erandi Extends WatchDogBaseFrame class Class to set settings of the
 *         system
 */
public class Settings extends WatchDogBaseFrame {

    private String filePath = VIDEO_STORAGE_PATH;
    OperatingMode operatingMode;
    String compressionMode = "";

    /**
     * Creates new form Settings
     */
    public Settings(WatchDogBaseFrame parentFrame) {
        super(parentFrame);
        initComponents();
        super.setCloseOperation();
        loadSettings();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jRadioButtonEfficiency = new javax.swing.JRadioButton();
        jRadioButtonNormal = new javax.swing.JRadioButton();
        jTextFieldPath = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jRadioButtonMedium = new javax.swing.JRadioButton();
        jRadioButtonLow = new javax.swing.JRadioButton();
        jRadioButtonHigh = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("DejaVu Serif", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("WatchDog - Settings");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Operating Mode");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Storage Options");

        jLabel4.setText("Storage Location");

        jButton2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton2.setText("Save Changes");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        buttonGroup.add(jRadioButtonEfficiency);
        jRadioButtonEfficiency.setSelected(true);
        jRadioButtonEfficiency.setText("Storage Efficiency Mode");
        jRadioButtonEfficiency.setActionCommand("");
        jRadioButtonEfficiency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonEfficiencyActionPerformed(evt);
            }
        });

        buttonGroup.add(jRadioButtonNormal);
        jRadioButtonNormal.setText("Normal Mode (24x7)");

        jTextFieldPath.setEditable(false);
        jTextFieldPath.setText("/home/erandi/NetBeansProjects/WatchDog/tmp/watchdog");

        jLabel5.setText("Compression Mode");

        buttonGroup1.add(jRadioButtonMedium);
        jRadioButtonMedium.setText("Medium");

        buttonGroup1.add(jRadioButtonLow);
        jRadioButtonLow.setSelected(true);
        jRadioButtonLow.setText("Low");

        buttonGroup1.add(jRadioButtonHigh);
        jRadioButtonHigh.setText("High");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonNormal)
                            .addComponent(jRadioButtonEfficiency)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(137, 137, 137)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jRadioButtonMedium)
                                            .addComponent(jRadioButtonHigh)
                                            .addComponent(jRadioButtonLow))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldPath, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jRadioButtonEfficiency))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonNormal)
                .addGap(34, 34, 34)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel5)
                        .addGap(1, 1, 1)
                        .addComponent(jRadioButtonLow)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonMedium)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonHigh)
                        .addContainerGap(63, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void loadSettings() {
        jTextFieldPath.setText(SettingsHandler.getSettings().getStoragePath());
        operatingMode = SettingsHandler.getSettings().getOperatingMode();
        compressionMode = SettingsHandler.getSettings().getCompressionMode();

        if (operatingMode == OperatingMode.HUMAN_PRESENCE_AWARE) {
            jRadioButtonEfficiency.setSelected(true);
        } else if (operatingMode == OperatingMode.NORMAL) {
            jRadioButtonNormal.setSelected(true);
        }

        if (compressionMode.equals("ultrafast")) {
            jRadioButtonLow.setSelected(true);
        } else if (compressionMode.equals("medium")) {
            jRadioButtonMedium.setSelected(true);
        } else {
            jRadioButtonHigh.setSelected(true);
        }
    }

    private void jRadioButtonEfficiencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonEfficiencyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonEfficiencyActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        /*
        Instead of using existing WatchDogContext object by calling WatchDogContext.getInstance(),
        new WatchDogContext object is created since it's safe to modify DB without risking existing object.
        After 'DB updating' is successful, setInstance() is called to modify static instance of WDC with
        modified settings.
         */
        WatchDogContext wdc = new WatchDogContext();

        if (jRadioButtonEfficiency.isSelected()) {
            operatingMode = OperatingMode.HUMAN_PRESENCE_AWARE;
            wdc.setOperatingMode(operatingMode);
        } else {
            operatingMode = OperatingMode.NORMAL;
            wdc.setOperatingMode(operatingMode);
        }

        if (jRadioButtonLow.isSelected()) {
            compressionMode = "ultrafast";
            wdc.setCompressionMode(compressionMode);
        } else if (jRadioButtonMedium.isSelected()) {
            compressionMode = "medium";
            wdc.setCompressionMode(compressionMode);
        } else {
            compressionMode = "veryslow";
            wdc.setCompressionMode(compressionMode);
        }
        wdc.setStoragePath(filePath);
        if (SettingsHandler.saveSettings(wdc)) {
            wdc = WatchDogContext.getInstance();
            wdc.setCompressionMode(compressionMode);
            wdc.setStoragePath(filePath);
            wdc.setOperatingMode(operatingMode);
            JOptionPane.showMessageDialog(null, "Settings saved successfully!", "Success!", 1);
            this.exitToParent(false);
        } else {
            JOptionPane.showMessageDialog(null, "Failed to save settings", "Fail!", 0);
            this.exitToParent(false);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Settings(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton jRadioButtonEfficiency;
    private javax.swing.JRadioButton jRadioButtonHigh;
    private javax.swing.JRadioButton jRadioButtonLow;
    private javax.swing.JRadioButton jRadioButtonMedium;
    private javax.swing.JRadioButton jRadioButtonNormal;
    private javax.swing.JTextField jTextFieldPath;
    // End of variables declaration//GEN-END:variables
}
